export * from './client.js';
export * from './crypto.js';
export * from './tenant.js';
export * from './audit.js';
export * from './usage.js';

// Re-export the generated Prisma types so consumers never import @prisma/client
// directly — one place to change if the generator output ever moves.
export {
  Prisma,
  Role,
  TenantStatus,
  SubscriptionStatus,
  MessageProviderType,
  ConnectionStatus,
  MessageType,
  IngestSource,
  MessageStatus,
  MessageCategory,
  Importance,
  FieldType,
  AutomationStatus,
  ProcessingMode,
  DateRangeMode,
  TriggerType,
  ActionType,
  RecordStatus,
  OutputType,
  OutputOperation,
  OutputStatus,
  UpdateStrategy,
  SyncStatus,
  ConflictResolution,
  RunTrigger,
  RunStatus,
  IntegrationType,
  IntegrationStatus,
  CredentialType,
  ExportStatus,
  WorkerStatus,
  HealthLayer,
  HealthState,
  NotificationSeverity,
} from '@prisma/client';

export type {
  User,
  Tenant,
  Membership,
  Plan,
  Subscription,
  Usage,
  WhatsAppConnection,
  ConnectionEvent,
  WhatsAppGroup,
  Message,
  MessageClassification,
  ExtractionSchema,
  ExtractionField,
  Automation,
  AutomationTrigger,
  AutomationAction,
  ExtractedRecord,
  RecordSource,
  RecordFieldEvent,
  Output,
  OutputTarget,
  OutputMapping,
  OutputSyncRecord,
  OutputVersion,
  OutputConflict,
  WorkflowRun,
  WorkflowRunStep,
  Integration,
  IntegrationCredential,
  Export,
  AuditLog,
  AIUsage,
  Worker,
  WorkerHeartbeat,
  HealthCheck,
  ApiKey,
  Notification,
} from '@prisma/client';
