import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  PageOrientation,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import type { SyncRow } from '@msgflow/types';

/**
 * Word (.docx) report generator.
 *
 * Mirrors the PDF renderer's contract: rows + column order in, an A4 document
 * out. Word documents exist for the clients whose downstream process is "open
 * it, adjust wording, forward it" — a spreadsheet is wrong for that and a PDF
 * cannot be edited, which is exactly the gap this fills.
 */

interface DocumentConfig {
  fileName?: string;
  title?: string;
  subtitle?: string;
  orientation?: 'portrait' | 'landscape';
}

function cellText(value: unknown): string {
  if (value === null || value === undefined) return '';
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

export async function renderRecordsDocx(
  rows: SyncRow[],
  columns: string[],
  config: DocumentConfig,
): Promise<Buffer> {
  const headerRow = new TableRow({
    tableHeader: true,
    children: columns.map(
      (col) =>
        new TableCell({
          children: [
            new Paragraph({
              children: [new TextRun({ text: col, bold: true, size: 18 })],
            }),
          ],
          shading: { fill: 'F1F5F9' },
        }),
    ),
  });

  const dataRows = rows.map(
    (row) =>
      new TableRow({
        children: columns.map(
          (col) =>
            new TableCell({
              children: [
                new Paragraph({
                  children: [new TextRun({ text: cellText(row.values[col]), size: 18 })],
                }),
              ],
            }),
        ),
      }),
  );

  const doc = new Document({
    creator: 'MsgFlow',
    title: config.title ?? 'MsgFlow Report',
    sections: [
      {
        properties: {
          page: {
            // A4 in twentieths of a point (docx's native unit).
            size: {
              width: config.orientation === 'portrait' ? 11906 : 16838,
              height: config.orientation === 'portrait' ? 16838 : 11906,
              orientation:
                config.orientation === 'portrait'
                  ? PageOrientation.PORTRAIT
                  : PageOrientation.LANDSCAPE,
            },
            margin: { top: 720, right: 720, bottom: 720, left: 720 },
          },
        },
        children: [
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: config.title ?? 'MsgFlow Report', size: 40 })],
          }),
          ...(config.subtitle
            ? [
                new Paragraph({
                  children: [
                    new TextRun({ text: config.subtitle, size: 20, color: '64748B' }),
                  ],
                }),
              ]
            : []),
          new Paragraph({ children: [] }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: [headerRow, ...dataRows],
          }),
          new Paragraph({
            alignment: AlignmentType.RIGHT,
            children: [
              new TextRun({
                text: `${rows.length} row(s) · generated by MsgFlow`,
                size: 16,
                color: '94A3B8',
              }),
            ],
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}
